[tool.poetry]
name = "openbb-cboe"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = "CBOE extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_cboe" }]

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
requests-cache = "^1.1.0"
openbb-core = "^1.0.0"
=======
aiohttp-client-cache = "^0.10.0"
aiosqlite = "^0.19.0"
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
cboe = "openbb_cboe:cboe_provider"
