[tool.poetry]
name = "openbb-technical"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.2"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = "Technical Analysis extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_technical" }]

[tool.poetry.dependencies]
<<<<<<< HEAD
python = ">=3.8,<3.12"   # scipy forces python <4.0 explicitly
scipy = "^1.10.1"
statsmodels = "^0.14.0"
scikit-learn = "^1.3.1"
openbb-core = "^1.0.0"
=======
python = ">=3.8,<3.12"  # scipy forces python <4.0 explicitly
scipy = "^1.10.1"
statsmodels = "^0.14.0"
scikit-learn = "^1.3.1"
pandas-ta = "^0.3.14b"
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
technical = "openbb_technical.technical_router:router"
