[tool.poetry]
name = "openbb-nasdaq"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.2"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = "Nasdaq extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_nasdaq" }]

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
openbb-core = "^1.0.0"
=======
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
random-user-agent = "^1.0.1"
nasdaq-data-link = "^1.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
nasdaq = "openbb_nasdaq:nasdaq_provider"
