[tool.poetry]
name = "openbb-biztoc"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = ""
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_biztoc" }]

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
openbb-core = "^1.0.0"
=======
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
requests-cache = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
biztoc = "openbb_biztoc:biztoc_provider"
