[tool.poetry]
name = "openbb-stockgrid"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = "stockgrid extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_stockgrid" }]

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
openbb-core = "^1.0.0"
=======
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_provider_extension"]
stockgrid = "openbb_stockgrid:stockgrid_provider"
