[tool.poetry]
name = "openbb-etf"
<<<<<<< HEAD
version = "1.0.0"
=======
version = "1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe
description = "ETF extension for OpenBB"
authors = ["OpenBB Team <hello@openbb.co>"]
readme = "README.md"
packages = [{ include = "openbb_etf" }]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
<<<<<<< HEAD
openbb-core = "^1.0.0"
=======
openbb-core = "^1.1.1"
>>>>>>> 7a07970fc8bd4b03ea459cb0d892005ff5130ffe

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."openbb_core_extension"]
etf = "openbb_etf.etf_router:router"
